name: CI Test Jest
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Packages
        run: npm install --silent
      - name: Run tests
        run: npm run test
